version: '3'

services: 
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "postgresdb"
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "cddcvfg"
    ports:
      - "5432:5432"
      